<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [

            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'user_management_create',],
            ['id' => 3, 'title' => 'user_management_edit',],
            ['id' => 4, 'title' => 'user_management_view',],
            ['id' => 5, 'title' => 'user_management_delete',],
            ['id' => 6, 'title' => 'permission_access',],
            ['id' => 7, 'title' => 'permission_create',],
            ['id' => 8, 'title' => 'permission_edit',],
            ['id' => 9, 'title' => 'permission_view',],
            ['id' => 10, 'title' => 'permission_delete',],
            ['id' => 11, 'title' => 'role_access',],
            ['id' => 12, 'title' => 'role_create',],
            ['id' => 13, 'title' => 'role_edit',],
            ['id' => 14, 'title' => 'role_view',],
            ['id' => 15, 'title' => 'role_delete',],
            ['id' => 16, 'title' => 'user_access',],
            ['id' => 17, 'title' => 'user_create',],
            ['id' => 18, 'title' => 'user_edit',],
            ['id' => 19, 'title' => 'user_view',],
            ['id' => 20, 'title' => 'user_delete',],
            ['id' => 21, 'title' => 'user_action_access',],
            ['id' => 22, 'title' => 'user_action_create',],
            ['id' => 23, 'title' => 'user_action_edit',],
            ['id' => 24, 'title' => 'user_action_view',],
            ['id' => 25, 'title' => 'user_action_delete',],
            ['id' => 26, 'title' => 'setting_access',],
            ['id' => 27, 'title' => 'contact_type_access',],
            ['id' => 28, 'title' => 'contact_type_create',],
            ['id' => 29, 'title' => 'contact_type_edit',],
            ['id' => 30, 'title' => 'contact_type_view',],
            ['id' => 31, 'title' => 'contact_type_delete',],
            ['id' => 32, 'title' => 'designation_type_access',],
            ['id' => 33, 'title' => 'designation_type_create',],
            ['id' => 34, 'title' => 'designation_type_edit',],
            ['id' => 35, 'title' => 'designation_type_view',],
            ['id' => 36, 'title' => 'designation_type_delete',],
            ['id' => 37, 'title' => 'address_type_access',],
            ['id' => 38, 'title' => 'address_type_create',],
            ['id' => 39, 'title' => 'address_type_edit',],
            ['id' => 40, 'title' => 'address_type_view',],
            ['id' => 41, 'title' => 'address_type_delete',],
            ['id' => 42, 'title' => 'country_access',],
            ['id' => 43, 'title' => 'country_create',],
            ['id' => 44, 'title' => 'country_edit',],
            ['id' => 45, 'title' => 'country_view',],
            ['id' => 46, 'title' => 'country_delete',],
            ['id' => 47, 'title' => 'state_access',],
            ['id' => 48, 'title' => 'state_create',],
            ['id' => 49, 'title' => 'state_edit',],
            ['id' => 50, 'title' => 'state_view',],
            ['id' => 51, 'title' => 'state_delete',],
            ['id' => 52, 'title' => 'city_access',],
            ['id' => 53, 'title' => 'city_create',],
            ['id' => 54, 'title' => 'city_edit',],
            ['id' => 55, 'title' => 'city_view',],
            ['id' => 56, 'title' => 'city_delete',],
            ['id' => 57, 'title' => 'contact_access',],
            ['id' => 58, 'title' => 'contact_create',],
            ['id' => 59, 'title' => 'contact_edit',],
            ['id' => 60, 'title' => 'contact_view',],
            ['id' => 61, 'title' => 'contact_delete',],
            ['id' => 62, 'title' => 'address_access',],
            ['id' => 63, 'title' => 'address_create',],
            ['id' => 64, 'title' => 'address_edit',],
            ['id' => 65, 'title' => 'address_view',],
            ['id' => 66, 'title' => 'address_delete',],
            ['id' => 67, 'title' => 'patient_access',],
            ['id' => 68, 'title' => 'patient_create',],
            ['id' => 69, 'title' => 'patient_edit',],
            ['id' => 70, 'title' => 'patient_view',],
            ['id' => 71, 'title' => 'patient_delete',],
            ['id' => 72, 'title' => 'diagnoses_type_access',],
            ['id' => 73, 'title' => 'diagnoses_type_create',],
            ['id' => 74, 'title' => 'diagnoses_type_edit',],
            ['id' => 75, 'title' => 'diagnoses_type_view',],
            ['id' => 76, 'title' => 'diagnoses_type_delete',],
            ['id' => 77, 'title' => 'diagnosis_access',],
            ['id' => 78, 'title' => 'diagnosis_create',],
            ['id' => 79, 'title' => 'diagnosis_edit',],
            ['id' => 80, 'title' => 'diagnosis_view',],
            ['id' => 81, 'title' => 'diagnosis_delete',],
            ['id' => 82, 'title' => 'treatment_type_access',],
            ['id' => 83, 'title' => 'treatment_type_create',],
            ['id' => 84, 'title' => 'treatment_type_edit',],
            ['id' => 85, 'title' => 'treatment_type_view',],
            ['id' => 86, 'title' => 'treatment_type_delete',],
            ['id' => 87, 'title' => 'treatment_stage_access',],
            ['id' => 88, 'title' => 'treatment_stage_create',],
            ['id' => 89, 'title' => 'treatment_stage_edit',],
            ['id' => 90, 'title' => 'treatment_stage_view',],
            ['id' => 91, 'title' => 'treatment_stage_delete',],
            ['id' => 92, 'title' => 'treatment_access',],
            ['id' => 93, 'title' => 'treatment_create',],
            ['id' => 94, 'title' => 'treatment_edit',],
            ['id' => 95, 'title' => 'treatment_view',],
            ['id' => 96, 'title' => 'treatment_delete',],
            ['id' => 97, 'title' => 'appointment_access',],
            ['id' => 98, 'title' => 'appointment_create',],
            ['id' => 99, 'title' => 'appointment_edit',],
            ['id' => 100, 'title' => 'appointment_view',],
            ['id' => 101, 'title' => 'appointment_delete',],
            ['id' => 102, 'title' => 'reschedule_reason_access',],
            ['id' => 103, 'title' => 'reschedule_reason_create',],
            ['id' => 104, 'title' => 'reschedule_reason_edit',],
            ['id' => 105, 'title' => 'reschedule_reason_view',],
            ['id' => 106, 'title' => 'reschedule_reason_delete',],
            ['id' => 107, 'title' => 'appointment_log_access',],
            ['id' => 108, 'title' => 'appointment_log_create',],
            ['id' => 109, 'title' => 'appointment_log_edit',],
            ['id' => 110, 'title' => 'appointment_log_view',],
            ['id' => 111, 'title' => 'appointment_log_delete',],
            ['id' => 112, 'title' => 'appointment_type_access',],
            ['id' => 113, 'title' => 'appointment_type_create',],
            ['id' => 114, 'title' => 'appointment_type_edit',],
            ['id' => 115, 'title' => 'appointment_type_view',],
            ['id' => 116, 'title' => 'appointment_type_delete',],
            ['id' => 117, 'title' => 'settings_access',],
            ['id' => 118, 'title' => 'settings_edit',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
